version: '3'

services:
  app:
    image: chenzhaoyu94/chatgpt-web # 总是使用 latest ,更新时重新 pull 该 tag 镜像即可
    ports:
      - 3002:3002
    environment:
      # 二选一
      #OPENAI_API_KEY: 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
      #OPENAI_API_KEY: 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
      # 二选一
      # winkyeme@gmail.com
      OPENAI_ACCESS_TOKEN: abc
      # API接口地址，可选，设置 OPENAI_API_KEY 时可用
      #OPENAI_API_BASE_URL: https://api.openai.com
      # API模型，可选，设置 OPENAI_API_KEY 时可用
      #OPENAI_API_MODEL: gpt-3.5-turbo
      # 反向代理，可选
      API_REVERSE_PROXY: https://ai.fakeopen.com/api/conversation
      #API_REVERSE_PROXY: https://chat.openai.com/backend-api/conversation
      # 访问权限密钥，可选
      #AUTH_SECRET_KEY: xxx
      # 超时，单位毫秒，可选
      TIMEOUT_MS: 60000
      # Socks代理，可选，和 SOCKS_PROXY_PORT 一起时生效
      #SOCKS_PROXY_HOST: ddpc.131433.xyz
      # Socks代理端口，可选，和 SOCKS_PROXY_HOST 一起时生效
      #SOCKS_PROXY_PORT: 27579
      # HTTPS 代理，可选，支持 http，https，socks5
      #HTTPS_PROXY: http://xxxx:7890